plugins {
    id 'com.android.library' version '9.0.0'
}

android {
    namespace 'git.artdeell.mojoexec'
    compileSdk 37

    defaultConfig {
        minSdk 21
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug {
            initWith release
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}